name: CD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        type: choice
        options:
          - develop
          - st
          - rt
      version:
        description: 'Enter version to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}  # Configura el ambiente dinámicamente
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: my-project

      - name: Load environment variables
        run: |
          echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" > my-project/.env
          echo "API_KEY_SID=${{ secrets.API_KEY_SID }}" >> my-project/.env
          echo "API_KEY_SECRET=${{ secrets.API_KEY_SECRET }}" >> my-project/.env
          echo "TWILIO_WORKSPACE_SID=${{ secrets.TWILIO_WORKSPACE_SID }}" >> my-project/.env
          echo "STAGE=${{ github.event.inputs.environment }}" >> my-project/.env

      - name: Extract service from tag
        id: extract-service
        run: |
          SERVICE=$(git tag -n99 | grep "${{ github.event.inputs.version }}" | awk -F ': ' '{print $2}')
          echo "SERVICE=${SERVICE}" >> $GITHUB_ENV

      - name: Deploy service
        run: |
          echo "Deploying service: ${{ env.SERVICE }}"
          if [ "${{ env.SERVICE }}" == "chat" ]; then
            #npm run deploy:chat -- --c "[B-389745] testing cicd" --skip-confirmation
          elif [ "${{ env.SERVICE }}" == "CCO MS" ]; then
            #npm run deploy:cco-ms -- --c "[B-389745] testing cicd" --skip-confirmation
          elif [ "${{ env.SERVICE }}" == "CCO PS" ]; then
            #npm run deploy:cco-ms -- --c "[B-389745] testing cicd" --skip-confirmation
          fi
        working-directory: my-project
