name: Conventional Commits Lint

on:
  push:
    branches:
      - feature/check-commits  # Cambia esto por la rama que deseas proteger
  pull_request:
    branches:
      - main  # Cambia esto por la rama que deseas proteger

jobs:
  lint-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para obtener el historial completo de commits

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Puedes cambiar la versión de Node.js según tus necesidades

      - name: Install dependencies
        working-directory: ./my-project  # Instala dependencias en el subdirectorio
        run: |
          npm install

      - name: Configure Husky
        run: |  # Configura Husky en la raíz del repositorio
          cd my-project
          npx husky install ../.husky  # Instala Husky en la raíz, pero usa la configuración del subdirectorio
          npx husky set ../.husky/commit-msg "cd my-project && npx commitlint --edit $1"
          npx husky set ../.husky/pre-push "cd my-project && npx commitlint --from=origin/main --to=HEAD"

      - name: Lint commits
        working-directory: ./my-project  # Ejecuta commitlint en el subdirectorio
        run: |
          npx commitlint --from=HEAD~1 --to=HEAD --verbose