name: CI Pipeline

on:
  push:
    branches:
      - feature/*
      - develop
      - rt
    paths:
      - 'my-project/resources/CCO MS/**'
      - 'my-project/resources/CCO PS/**'
      - 'my-project/resources/chat/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Detect changes in CCO MS
      id: detect-cco-ms
      run: |
        if git diff --name-only HEAD^ HEAD | grep -q 'my-project/resources/CCO MS/'; then
          echo "::set-output name=changed::true"
          echo "Los cambios fueron hechos en la carpeta CCO MS"
        else
          echo "::set-output name=changed::false"
        fi

    - name: Detect changes in CCO PS
      id: detect-cco-ps
      run: |
        if git diff --name-only HEAD^ HEAD | grep -q 'my-project/resources/CCO PS/'; then
          echo "::set-output name=changed::true"
          echo "Los cambios fueron hechos en la carpeta CCO PS"
        else
          echo "::set-output name=changed::false"
        fi

    - name: Detect changes in chat
      id: detect-chat
      run: |
        if git diff --name-only HEAD^ HEAD | grep -q 'my-project/resources/chat/'; then
          echo "::set-output name=changed::true"
          echo "Los cambios fueron hechos en la carpeta chat"
        else
          echo "::set-output name=changed::false"
        fi