name: CI Pipeline

on:
  push:
    branches:
      - feature/*
      - develop
      - rt
    paths:
      - 'my-project/resources/CCO MS/**'
      - 'my-project/resources/CCO PS/**'
      - 'my-project/resources/chat/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch full history for diff
        run: git fetch --unshallow

      - name: Detect changes
        id: detect-changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "Changed files: $CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -q "my-project/resources/CCO MS/"; then
            echo "folder=CCO MS" >> $GITHUB_ENV
            echo "Los cambios fueron hechos en la carpeta CCO MS"
          elif echo "$CHANGED_FILES" | grep -q "my-project/resources/CCO PS/"; then
            echo "folder=CCO PS" >> $GITHUB_ENV
            echo "Los cambios fueron hechos en la carpeta CCO PS"
          elif echo "$CHANGED_FILES" | grep -q "my-project/resources/chat/"; then
            echo "folder=chat" >> $GITHUB_ENV
            echo "Los cambios fueron hechos en la carpeta chat"
          else
            echo "No relevant changes detected."
            exit 1

      - name: Log result
        run: |
          echo "Folder changed: ${{ env.folder }}"
