name: Concurrencia Manual

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  concurrencia:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: false
    steps:
      - name: Imprimir Nombre del Grupo de Concurrencia
        run: |
          echo "Nombre del grupo de concurrencia: ci-${{ github.head_ref || github.ref_name }}"
          echo "El valor de github.head_ref es: ${{ github.head_ref }}"
          echo "El valor de github.ref_name es: ${{ github.ref_name }}"