name: Deploy Manual con Concurrencia

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Selecciona el entorno'
        required: true
        type: string
        options:
          - DEV
          - ST
          - RT

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    concurrency:
      group: CD-${{ github.event.inputs.env }}
      cancel-in-progress: false
    steps:
      - name: Imprimir Nombre del Grupo de Concurrencia y ENV
        run: |
          echo "Nombre del grupo de concurrencia: CD-${{ github.event.inputs.env }}"
          echo "Valor de la variable ENV: ${{ github.event.inputs.env }}"