name: Create Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Versión del tag (ej. 1.2.3)'
        required: true
        type: string
      branch:
        description: 'Branch donde se creará el tag'
        required: true
        type: choice
        options:
          - develop
          - main

jobs:
  create_tag:
    name: Create Tag in Specified Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0  # Descarga todo el historial y tags

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create and Push Tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin --tags  # Empuja todos los tags