name: Create Annotated Tag 

on:
  push:
    branches:
      - feature/event-folders  # Trigger the workflow on push to the feature/event-folders branch

jobs:
  create-tag:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: develop  # Define an environment variable 'develop'

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Necesario para obtener el historial completo de commits y tags

    - name: Fetch all branches and tags
      run: |
        # Fetch all branches and tags from the remote
        git fetch --all

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Get the commit SHA for feature/event-folders and main
      run: |
        # Get the current commit SHA of the feature/event-folders branch
        #COMMIT_SHA_FEATURE=$(git rev-parse origin/feature/event-folders)
        
        # Get the commit SHA of the main branch
        COMMIT_SHA_MAIN=$(git rev-parse origin/main)

        #echo "COMMIT_SHA_FEATURE=${COMMIT_SHA_FEATURE}"
        echo "COMMIT_SHA_MAIN=${COMMIT_SHA_MAIN}"

    - name: Create annotated tag
      run: |
        # Create an annotated tag with the environment in the message
        #git tag -a v1.0.0-${{ env.ENVIRONMENT }} -m "Annotated tag for feature/event-folders on ${ENVIRONMENT}" $COMMIT_SHA_FEATURE
        git tag -a v1.0.0-${{ env.ENVIRONMENT }}-main -m "Annotated tag for main branch on ${ENVIRONMENT}" $COMMIT_SHA_MAIN

    - name: Push the tag
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}  # Usar el PAT almacenado como secreto
      run: |
        # Configurar la URL del repositorio con el PAT para autenticación
        git remote set-url origin https://xle29111:${{ secrets.PAT }}@github.com/xle29111/twilio-chat.git
        
        # Push the tags to the remote repository
        git push origin v1.0.0-${{ env.ENVIRONMENT }}
        #git push origin v1.0.0-${{ env.ENVIRONMENT }}-main
