name: Create Version Tag

on:
  push:
    branches:
      - feature/event-folders  # Trigger the workflow on push to the feature/event-folders branch

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Generate Version using commit count
      id: version
      uses: anothrNick/github-tag-action@v1
      with:
        tag_prefix: 'v'  # Prefix for the version (e.g. v1.0.0)

    - name: Create an annotated tag
      run: |
        VERSION=${{ steps.version.outputs.new_tag }}
        echo "Generated version: $VERSION"

        # Create an annotated tag
        git tag -a $VERSION -m "Version $VERSION"

    - name: Push the tag
      run: |
        # Authenticate using the Personal Access Token (PAT)
        git remote set-url origin https://xle29111:${{ secrets.PAT }}@github.com/xle29111/twilio-chat.git
        git push origin $VERSION
