name: Create Version Tag

on:
  push:
    branches:
      - feature/event-folders  # Trigger the workflow on push to the feature/event-folders branch

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install versioneer

    - name: Generate Version using versioneer
      id: version
      run: |
        VERSION=$(python -c "import versioneer; print(versioneer.get_version())")
        echo "Generated version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create an annotated tag
      run: |
        VERSION=${{ env.VERSION }}
        git tag -a $VERSION -m "Version $VERSION"

    - name: Push the tag
      run: |
        # Authenticate using the Personal Access Token (PAT)
        git remote set-url origin https://xle29111:${{ secrets.PAT }}@github.com/xle29111/twilio-chat.git
        git push origin $VERSION