name: Build Deployment Message

on:
  push:
    branches:
      - feature/*
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-message:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Obtener el mensaje del último commit (para feature) o el título del PR (para develop)
      - name: Get message based on branch
        id: get-message
        run: |
          if [[ "${{ github.ref }}" == refs/heads/feature/* ]]; then
            MESSAGE="${{ github.event.head_commit.message }}"
            echo "Using commit message: $MESSAGE"
          elif [[ "${{ github.ref }}" == refs/heads/develop ]]; then
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              MESSAGE="${{ github.event.pull_request.title }}"
              echo "Using PR title: $MESSAGE"
            else
              MESSAGE="${{ github.event.head_commit.message }}"
              echo "Using commit message (develop branch, non-PR event): $MESSAGE"
            fi
          else
            echo "Unsupported branch"
            exit 1
          fi
          echo "MESSAGE=$MESSAGE" >> $GITHUB_ENV

      # Paso 3: Extraer la versión del package.json
      - name: Get version from package.json
        id: package-version
        run: |
          VERSION=$(jq -r .version my-project/package.json)
          echo "Package Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Paso 4: Determinar la etiqueta (DEV para feature, ST para develop)
      - name: Determine tag
        id: determine-tag
        run: |
          if [[ "${{ github.ref }}" == refs/heads/feature/* ]]; then
            TAG="DEV"
          elif [[ "${{ github.ref }}" == refs/heads/develop ]]; then
            TAG="ST"
          else
            TAG=""
          fi
          echo "Tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      # Paso 5: Construir el mensaje completo y mostrarlo por consola
      - name: Build and display full message
        run: |
          echo "MESSAGE: $MESSAGE"
          echo "VERSION: $VERSION"
          echo "TAG: $TAG"
          FULL_MESSAGE="$MESSAGE - v$VERSION $TAG"
          echo "Full Message: $FULL_MESSAGE"