name: Tag on Push to Develop

on:
  push:
    branches:
      - develop

jobs:
  tag-on-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Fetch all branches and tags
      run: git fetch --all --tags

    - name: Identify feature branch and create new tag
      run: |
        # Identify the merge commit
        MERGE_COMMIT=$(git log --merges -1 --pretty=format:'%H')
        
        # Identify the feature branch that was merged
        FEATURE_BRANCH=$(git name-rev --name-only $MERGE_COMMIT^2)
        
        if [[ "$FEATURE_BRANCH" != feature/* ]]; then
          echo "No feature branch found for the current commit."
          exit 1
        fi
        
        echo "Feature branch: $FEATURE_BRANCH"
        
        # Get the last commit message from the feature branch
        LAST_COMMIT_MSG=$(git log -1 --pretty=format:'%s' $FEATURE_BRANCH)
        
        # Get the latest tag
        LATEST_TAG=$(git describe --tags --abbrev=0)
        
        # Create a new tag
        NEW_TAG=$(echo $LATEST_TAG | awk -F. -v OFS=. '{$NF += 1 ; print}')
        git tag -a "$NEW_TAG" -m "$LAST_COMMIT_MSG"
        git push origin "$NEW_TAG"
        
        # Output the new tag
        echo "New tag $NEW_TAG created with message: $LAST_COMMIT_MSG"