name: Tag on Push to Develop

on:
  push:
    branches:
      - develop

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get merged branch name
        id: merged_branch
        run: |
          MERGED_BRANCH=$(git log --merges -n 1 --pretty=format:'%s' | grep -oE 'feature/[a-zA-Z0-9._-]+' || echo "")
          echo "MERGED_BRANCH=$MERGED_BRANCH" >> $GITHUB_ENV

      - name: Validate merged branch
        run: |
          if [ -z "$MERGED_BRANCH" ]; then
            echo "No feature branch detected. Exiting..."
            exit 1
          fi

      - name: Get latest commit message from feature branch
        id: commit_message
        run: 
