name: Tag on Push to Develop

on:
  push:
    branches:
      - develop

jobs:
  tag-on-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Identify feature branch
      run: echo "FEATURE_BRANCH=$(git branch --contains $(git rev-parse HEAD) | grep 'feature/' | sed 's/* //')" >> $GITHUB_ENV

    - name: Get the last commit message from the feature branch
      id: last-commit-message
      run: |
        LAST_COMMIT_MSG=$(git log -1 --pretty=format:'%s' origin/${{ env.FEATURE_BRANCH }})
        echo "LAST_COMMIT_MSG=${LAST_COMMIT_MSG}" >> $GITHUB_ENV

    - name: Get the latest tag
      id: get-latest-tag
      run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Create new tag
      id: create-tag
      run: |
        NEW_TAG=$(echo ${{ steps.get-latest-tag.outputs.LATEST_TAG }} | awk -F. -v OFS=. '{$NF += 1 ; print}')
        git tag -a "$NEW_TAG" -m "${{ env.LAST_COMMIT_MSG }}"
        git push origin "$NEW_TAG"

    - name: Output the new tag
      run: echo "New tag ${{ steps.create-tag.outputs.NEW_TAG }} created with message: ${{ env.LAST_COMMIT_MSG }}"