name: Build Deployment Message

on:
  push:
    branches:
      - feature/*
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-message:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Detectar la carpeta afectada
      - name: Detect affected folder
        id: detect-folder
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "Changed files: $CHANGED_FILES"

          case "$CHANGED_FILES" in
            *my-project/resources/CCO\ MS/*)
              FOLDER="CCO MS"
              ;;
            *my-project/resources/CCO\ PS/*)
              FOLDER="CCO PS"
              ;;
            *my-project/resources/chat/*)
              FOLDER="chat"
              ;;
            *)
              FOLDER="unknown"
              ;;
          esac

          echo "Affected folder: $FOLDER"
          echo "FOLDER=$FOLDER" >> $GITHUB_ENV

      # Paso 3: Obtener el mensaje del último commit (para feature) o la descripción del PR (para develop)
      - name: Get message based on branch
        id: get-message
        run: |
          BRANCH="${{ github.ref }}"
          case "$BRANCH" in
            refs/heads/feature/*)
              MESSAGE="${{ github.event.head_commit.message }}"
              echo "Using commit message: $MESSAGE"
              ;;
            refs/heads/develop)
              MESSAGE="${{ github.event.pull_request.title }}"
              echo "Using PR description: $MESSAGE"
              ;;
            *)
              echo "Unsupported branch"
              exit 1
              ;;
          esac
          echo "MESSAGE=$MESSAGE" >> $GITHUB_ENV

      # Paso 4: Extraer la versión del package.json
      - name: Get version from package.json
        id: package-version
        run: |
          VERSION=$(jq -r .version my-project/package.json)
          echo "Package Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Paso 5: Determinar la etiqueta (DEV para feature, ST para develop)
      - name: Determine tag
        id: determine-tag
        run: |
          BRANCH="${{ github.ref }}"
          case "$BRANCH" in
            refs/heads/feature/*)
              TAG="DEV"
              ;;
            refs/heads/develop)
              TAG="ST"
              ;;
            *)
              TAG=""
              ;;
          esac
          echo "Tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      # 
