name: Print Actor If Match

on:
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  print-actor:
    runs-on: ubuntu-latest
    steps:
      - name: Check Actor and Print
        if: ${{ github.actor == 'xaencarnacion' }}
        run: echo "The actor is ${{ github.actor }}"
