name: Generating Pre-release

on:
  workflow_dispatch:
    inputs:
      new_release_tag:
        description: 'Enter the new release tag version'
        required: true

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Get latest release
      env:
        GH_TOKEN: ${{ github.token }}  
      run: |
        # Obtiene el tag del último release
        latest_release=$(gh release view --json tagName -q '.tagName')

        echo "Latest release: $latest_release"
        
        # Exporta latest_release como variable de ambiente
        echo "LATEST_RELEASE=$latest_release" >> $GITHUB_ENV  

    - name: Generate release tags list
      shell: bash
      run: |
        new_release_tag=${{ github.event.inputs.new_release_tag }}
        latest_release=$LATEST_RELEASE

        # Obtiene los tags de los releases intermedios
        release_tags=$(git tag --sort=-v:refname | awk -v latest=$latest_release -v new=$new_release_tag '{
          if ($0 <= new && $0 > latest) print $0
        }' | tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')

        # Exporta release_tags como variable de ambiente
        echo "RELEASE_TAGS=$release_tags" >> $GITHUB_ENV

    - name: Create release notes
      id: create_release_notes
      shell: bash
      run: |
        new_release_tag=${{ github.event.inputs.new_release_tag }}
        latest_release=$LATEST_RELEASE
        release_tags=$RELEASE_TAGS

        # Obtiene las carpetas modificadas
        MODIFIED_FOLDERS=$(git diff --name-only $latest_release $new_release_tag -- my-project/resources | awk -F/ '{print $3}' | sort -u | tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')

        # Crea un archivo temporal para las notas del release
        echo "Changes detected in this release:" > release_notes.txt
        echo "" >> release_notes.txt
        echo "Modified folders: $MODIFIED_FOLDERS" >> release_notes.txt
        echo "" >> release_notes.txt
        echo "Changes in this release: $release_tags" >> release_notes.txt

        # Muestra el contenido del archivo de notas del release
        cat release_notes.txt

    - name: Create new release using GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.event.inputs.new_release_tag }} \
          --title "${{ github.event.inputs.new_release_tag }}" \
          --notes-file release_notes.txt \
          --prerelease