name: Tag on Merge to Develop

on:
  push:
    branches:
      - develop

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Tag with Commit Message
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          git tag -a "${TAG_NAME}" -m "${LAST_COMMIT_MESSAGE}"
          git push origin "${TAG_NAME}"
          echo "Created Tag ${TAG_NAME} with message: ${LAST_COMMIT_MESSAGE}"