name: Tag on Merge to Develop

on:
  push:
    branches:
      - develop

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get last commit message from feature branch
        id: get_commit_message
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "LAST_COMMIT_MESSAGE=${LAST_COMMIT_MESSAGE}" >> $GITHUB_ENV

      - name: Create Tag
        id: create_tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          git tag -a "${TAG_NAME}" -m "${{ env.LAST_COMMIT_MESSAGE }}"
          git push origin "${TAG_NAME}"

      - name: Output Tag Name
        run: echo "Created Tag ${{ steps.create_tag.outputs.tag_name }}"