name: Detect Changes Between Tags

on:
  workflow_dispatch:
    inputs:
      new_release_tag:
        description: 'Enter the new tag version (e.g., v1.1.4)'
        required: true

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest release tag
      id: get_latest_release
      shell: bash
      run: |
        latest_release=$(git describe --tags `git rev-list --tags --max-count=1 --no-merges --exclude="*-pre-release"`)
        echo "Latest release: $latest_release"
        echo "::set-output name=latest_release::$latest_release"

    - name: Detect changes between tags
      id: detect_changes
      shell: bash
      run: |
        new_release_tag=${{ github.event.inputs.new_release_tag }}
        latest_release=${{ steps.get_latest_release.outputs.latest_release }}

        echo "New release: $new_release_tag"
        echo "Latest release: $latest_release"
        
        echo "Comparing changes between $new_release_tag and $latest_release..."

        changes=$(git diff --name-only $latest_release $new_release_tag -- my-project/resources | awk -F/ '{print $3}' | sort -u | tr '\n' ',' | sed 's/,$//')
        echo "CHANGES=$(echo $changes)" >> $GITHUB_ENV
        echo "Detected changes: $changes"

    - name: Create new release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.new_release_tag }}
        release_name: ${{ github.event.inputs.new_release_tag }}
        body: |
          Changes detected in this release:
          ${{ env.CHANGES }}