name: Retrieve and Store Secrets

on:
  push:
    branches:
      - feature/*
      - develop
      - rt

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Retrieve Secrets from GitHub
        run: |
          echo "SECRET_KEY_1=${{ secrets.ACCOUNT_SID }}" >> $GITHUB_ENV
          echo "SECRET_KEY_2=${{ secrets.AUTH_TOKEN }}" >> $GITHUB_ENV

      - name: Display Secrets from GitHub Variables
        run: |
          echo "Secret Key 1: $SECRET_KEY_1"
          echo "Secret Key 2: $SECRET_KEY_2"

      - name: Save Secrets to .env File
        run: |
          echo "SECRET_KEY_1=$SECRET_KEY_1" > .env
          echo "SECRET_KEY_2=$SECRET_KEY_2" >> .env

      - name: Display Secrets from .env File
        run: |
          cat .env
