name: Deploy Selected Services

on:
  workflow_dispatch:
    inputs:
      deploy_service_1:
        description: 'Deploy Servicio 1'
        required: false
        type: boolean
      deploy_service_2:
        description: 'Deploy Servicio 2'
        required: false
        type: boolean
      deploy_service_3:
        description: 'Deploy Servicio 3'
        required: false
        type: boolean

jobs:
  show-selected-services:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar servicios seleccionados
        run: |
          echo "Servicios seleccionados:"
          if [ "${{ inputs.deploy_service_1 }}" == "true" ]; then
            echo "- Servicio 1"
          fi
          if [ "${{ inputs.deploy_service_2 }}" == "true" ]; then
            echo "- Servicio 2"
          fi
          if [ "${{ inputs.deploy_service_3 }}" == "true" ]; then
            echo "- Servicio 3"
          fi
