name: Deploy Selected Services

on:
  workflow_dispatch:
    inputs:
      deploy_service_1:
        description: 'Servicio 1'
        required: false
        type: boolean
      deploy_service_2:
        description: 'Servicio 2'
        required: false
        type: boolean
      deploy_service_3:
        description: 'Servicio 3'
        required: false
        type: boolean

permissions:
  contents: write  # Necesario para hacer push al repo

jobs:
  write-and-show-services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deploy-prod
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false
		      ref: deploy-prod

      - name: Inicializar archivo de servicios
        run: echo -n "" > flows_to_deploy.txt

      - name: Escribir servicios seleccionados
        run: |
          echo "Servicios seleccionados:"
          
          if [ "${{ inputs.deploy_service_1 }}" == "true" ]; then
            echo "- Servicio 1"
            echo "servicio-1" >> flows_to_deploy.txt
          fi
          if [ "${{ inputs.deploy_service_2 }}" == "true" ]; then
            echo "- Servicio 2"
            echo "servicio-2" >> flows_to_deploy.txt
          fi
          if [ "${{ inputs.deploy_service_3 }}" == "true" ]; then
            echo "- Servicio 3"
            echo "servicio-3" >> flows_to_deploy.txt
          fi

      - name: Mostrar contenido final del archivo
        run: |
          echo "Contenido de flows_to_deploy.txt:"
          cat flows_to_deploy.txt

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Hacer commit y push del archivo actualizado
        run: |
          git add flows_to_deploy.txt
          git commit -m "Update flows_to_deploy.txt desde workflow manual"
          git push origin HEAD
