name: Imprimir nombre del branch

on:
  workflow_dispatch:

jobs:
  imprimir-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar nombre del branch (excepto en 'rt' y 'main')
        if: ${{ github.ref_name != 'rt' && github.ref_name != 'main' }}
        run: |
          echo "Branch seleccionado: ${{ github.ref_name }}"
