name: Deploy Node.js Application

on:
  push:
    branches:
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Obtener el mensaje de commit y extraer el número de historia y el comentario
      - name: Extract story number and comment from commit message
        id: extract-commit
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          echo "Commit Message: $COMMIT_MESSAGE"

          # Expresión regular corregida para extraer el número de historia y el comentario
          if [[ "$COMMIT_MESSAGE" =~ \[([0-9]+)\]\ (.+) ]]; then
            STORY_NUMBER="${BASH_REMATCH[1]}"
            COMMENT="${BASH_REMATCH[2]}"
            echo "Story Number: $STORY_NUMBER"
            echo "Comment: $COMMENT"
          else
            echo "No se encontró un número de historia y comentario en el mensaje de commit para este proyecto."
            exit 1
          fi

          # Exportar las variables para usarlas en pasos posteriores
          echo "STORY_NUMBER=$STORY_NUMBER" >> $GITHUB_ENV
          echo "COMMENT=$COMMENT" >> $GITHUB_ENV

      # Paso 3: Mostrar las variables extraídas por consola
      - name: Print extracted variables
        run: |
          echo "Número de historia: $STORY_NUMBER"
          echo "Comentario de cambios: $COMMENT"

      # Paso 4: Ejecutar el comando de despliegue con las variables extraídas
      #- name: Deploy application
      #  run: npm run deploy:cco-ps -- -c "[#$STORY_NUMBER] $COMMENT"