name: Deploy Node.js Repository

on:
  push:
    branches:
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Paso 2: Extraer el número de la historia y el comentario del mensaje de commit
      - name: Extract story number and comment from commit message
        id: extract_commit_info
        run: |
          # Obtener el mensaje del commit más reciente
          COMMIT_MSG=$(git log -1 --pretty=%B)

          # Usar expresiones regulares para extraer el número de historia y el comentario
          STORY_NUMBER=$(echo "$COMMIT_MSG" | grep -oP '#\d+' | head -n 1)  # Extrae el primer #número
          COMMENT=$(echo "$COMMIT_MSG" | sed -n 's/.*#\d\+ \(.*\)/\1/p')  # Extrae el comentario después del #story

          # Mostrar las variables por consola
          echo "Story Number: $STORY_NUMBER"
          echo "Comment: $COMMENT"

          # Pasar las variables al entorno
          echo "STORY_NUMBER=$STORY_NUMBER" >> $GITHUB_ENV
          echo "COMMENT=$COMMENT" >> $GITHUB_ENV

      # Paso 3: Instalar Node.js v18
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Paso 4: Instalar dependencias
      - name: Install Dependencies
        run: |
          cd my-project
          npm install

      # Paso 5: Ejecutar el comando de despliegue, pasando las variables extraídas
      #- name: Deploy to production
      #  run: |
      #    cd my-project
      #    npm run deploy:cco-ps -- -c"Story Number: ${{ env.STORY_NUMBER }} - Comment: ${{ env.COMMENT }}"

