name: Tag Modified Folders on Merge

on:
  push:
    branches:
      - develop

jobs:
  tag_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR author
        run: |
          PR_AUTHOR=$(git log -1 --pretty=format:'%an')
          echo "PR_AUTHOR=$PR_AUTHOR" >> $GITHUB_ENV

      - name: Get modified folders
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep '^my-project/resources/' || true)
          if [ -n "$CHANGED_FILES" ]; then
            MODIFIED_FOLDERS=$(echo "$CHANGED_FILES" | awk -F'/' '{print $3}' | sort -u | paste -sd ', ' - | sed 's/[[:space:]]*$//')
            echo "MODIFIED_FOLDERS=$MODIFIED_FOLDERS" >> $GITHUB_ENV
          else
            echo "MODIFIED_FOLDERS=None" >> $GITHUB_ENV
          fi

      - name: Extract package version
        run: |
          PACKAGE_VERSION=$(jq -r .version my-project/package.json)
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Get latest tag
        id: latest_tag
        run: |
          LATEST_TAG=$(git tag --list 'v[0-9]*' --sort=-v:refname | head -n 1 || echo 'v0.0.0')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Generate new tag
        id: new_tag
        run: |
          latest_tag="${LATEST_TAG}"
          IFS='.' read -r -a parts <<< "${latest_tag#v}"
          new_tag="v${parts[0]}.$((parts[1] + 1)).0"
          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV

      - name: Create and push new tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          TAG_MESSAGE=$(printf "Modified folders: %s\nPackage version: %s\nPR Author: %s" "$MODIFIED_FOLDERS" "$PACKAGE_VERSION" "$PR_AUTHOR")
          git tag -a "$NEW_TAG" -m "$TAG_MESSAGE"
          git push origin "$NEW_TAG"