name: Find Tag Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag a buscar (ej. v1.2.3)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  check_tag:
    name: Check Tag in Branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Obtiene todos los tags y referencias

      - name: Find Tag in Branches
        id: find_tag
        run: |
          TAG="${{ github.event.inputs.version }}"
          BRANCHES=("main" "develop" "rt")
          FOUND_IN=""

          for BRANCH in "${BRANCHES[@]}"; do
            if git branch -r --contains "refs/tags/$TAG" | grep -q "origin/$BRANCH"; then
              FOUND_IN="$BRANCH"
              break
            fi
          done

          if [[ -z "$FOUND_IN" ]]; then
            echo "El tag $TAG no se encuentra en ninguna de las ramas especificadas."
            exit 1
          else
            echo "El tag $TAG se encuentra en la rama: $FOUND_IN"
            echo "branch_found=$FOUND_IN" >> $GITHUB_OUTPUT
          fi

      - name: Checkout desde main
        if: steps.find_tag.outputs.branch_found == 'main'
        run: |
          git checkout main
          echo "Se hizo checkout desde la rama main"

      - name: Checkout desde rt
        if: steps.find_tag.outputs.branch_found == 'rt'
        run: |
          git checkout rt
          echo "Se hizo checkout desde la rama rt"
