name: Find Tag Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag to search for (e.g. v1.2.3)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  check_tag:
    name: Check Tag in Branches
    runs-on: ubuntu-latest
    steps:
      - name: Initial Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all tags and references
          show-progress: false

      - name: Find Tag in Branches
        id: find_tag
        run: |
          TAG="${{ github.event.inputs.version }}"
          STATIC_BRANCHES=("main" "develop" "rt")
          HOTFIX_BRANCHES=$(git branch -r | grep 'origin/hotfix/' | sed 's|origin/||')

          # Combine all branches to check
          BRANCHES=("${STATIC_BRANCHES[@]}" ${HOTFIX_BRANCHES})
          FOUND_IN=""

          for BRANCH in "${BRANCHES[@]}"; do
            if git branch -r --contains "refs/tags/$TAG" | grep -q "origin/$BRANCH"; then
              FOUND_IN="$BRANCH"
              break
            fi
          done

          if [[ -z "$FOUND_IN" ]]; then
            echo "Tag $TAG was not found in any of the specified branches."
            exit 1
          else
            echo "Tag $TAG was found in branch: $FOUND_IN"
            echo "branch_found=$FOUND_IN" >> $GITHUB_OUTPUT
          fi

      - name: Checkout from detected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.find_tag.outputs.branch_found }}
          fetch-depth: 0
          show-progress: false
